do

	XPRACTICE.MULTIPLAYER.PREFIX="XP"

	if(not XPRACTICE.MULTIPLAYER.LISTENER)then
		XPRACTICE.MULTIPLAYER.LISTENER=CreateFrame("Frame")
		XPRACTICE.MULTIPLAYER.LISTENER:RegisterEvent("CHAT_MSG_ADDON")
		XPRACTICE.MULTIPLAYER.LISTENER:RegisterEvent("GROUP_ROSTER_UPDATE")
		XPRACTICE.MULTIPLAYER.LISTENER:SetScript("OnEvent",XPRACTICE.MULTIPLAYER.EventHandler)
		C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYER.PREFIX)
	end	
	
	
	
	
end